### ISSUE TITLE
'Upsample' warnings and video decode errors

### ISSUE THREAD

**Issue by k-zha14** [TimothyHTimothy/FAST-VQA#14]
Hi, guys! 
Thank you for your work. My environment is: torch 1.10, torchvision 0.11. 
After runing 'python new_train.py -o options/fast/fast-b.yml' code, I meet these warnings and errors:
1. UpSample  warnings
![image](https://user-images.githubusercontent.com/32434681/186844397-814e38ba-909f-4207-bfa7-ec15b073f0b7.png)

2. Decode errors
![image](https://user-images.githubusercontent.com/32434681/186844458-5f87aef3-6eff-47c4-b786-6b3f6a0ec914.png)
![image](https://user-images.githubusercontent.com/32434681/186844502-83e78e84-660a-41c1-9dab-2c5ded65bc49.png)

Although the traing process seems still running, I wanna know whether these are normal cases or NOT. 
Thanks for your help

**Comment by teowu** [comment]
These are not affecting...sadly we also do not know how to mute both of them off...
Some tips that might help:
The first comes from `torchvision` and can be muted by `py4j` to set log level at error, but the second warning comes from `ffmpeg` and cannot be modified by us also...
