### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by cs19469** [TimothyHTimothy/FAST-VQA#15]
swin_tiny_grpb
None False
Setting backbone: fragments_backbone

Segmentation fault

When i run the vaq.py, somenthing like this

**Comment by teowu** [comment]
Can you tell me your hardware and software versions?
You are not the only one who meet the problem, and I am trying to solve this together for you.

**Comment by cs19469** [comment]
Thank you for your reply.
my device is:
Tesla K80, cuda 10.2, python3.8,
I have no idea about this, but  it works now!

**Comment by woshin** [comment]
there is something wrong with decord and torch packages.  
crash at 
`evaluator = DiViDeAddEvaluator(**opt["model"]["args"]).to(args.device)`

simplest solution is import torch first instead of decord. it works for me, but I have not found the root cause)
