### ISSUE TITLE
the score

### ISSUE THREAD

**Issue by cs19469** [TimothyHTimothy/FAST-VQA#16]
I have run the default one, and get a score around 0.133. Is the predicted score of the video?  I find the groundtruth is 2.88 in the txt, Is there any connection between them?

**Comment by teowu** [comment]
The scores are in a different scale with the original MOS labels, yet the relation between different scores are kept not changed. A better way to understand them is to run the script on two different videos and see which one is better.
You may also check previous issues on how to remap the scores back.
