### ISSUE TITLE
Pre-trained weights are not accessible; links are dead

### ISSUE THREAD

**Issue by JoshuaEbenezer** [TimothyHTimothy/FAST-VQA#17]
Hi
I'm reopening this issue because this link is dead now. https://github.com/TimothyHTimothy/BasicVQA/releases/download/v0.22.0/ gives a 404 error. Can you please provide an updated link? Also note that from fastvqa import deep_end_to_end_vqa; deep_end_to_end_vqa(True) fails.

**Comment by teowu** [comment]
Hi! Sorry about the inconvenience. The code you reached might be some deprecated from the old version.
May I know whether branch are you working on?
For pretrained weights, you may take a look at the refactored release: [here](https://github.com/teowu/FAST-VQA-and-FasterVQA/releases/tag/v2.0.1) with all "living" weights.

**Comment by teowu** [comment]
Please let me know whether this can solve your problem!

**Comment by JoshuaEbenezer** [comment]
I'm on the dev branch. I got the weights from v2.0.1. I think you should update the instructions here: https://github.com/teowu/FAST-VQA-and-FasterVQA/tree/dev/pretrained_weights. Thanks!

**Comment by teowu** [comment]
Thank you for your suggestion! Have removed the erroneous instructions.
