### ISSUE TITLE
Correcting reference

### ISSUE THREAD

**Issue by vztu** [TimothyHTimothy/FAST-VQA#2]
Hi @TimothyHTimothy, thanks for the great work on VQA! 

I found that you're citing the wrong reference paper (conference version) for our RAPIQUE model. Could you help correct to cite the right journal version instead in the camera-ready? Thank you very much for your consideration!

```
@article{tu2021rapique,
  title={RAPIQUE: Rapid and accurate video quality prediction of user generated content},
  author={Tu, Zhengzhong and Yu, Xiangxu and Wang, Yilin and Birkbeck, Neil and Adsumilli, Balu and Bovik, Alan C},
  journal={IEEE Open Journal of Signal Processing},
  volume={2},
  pages={425--440},
  year={2021},
  publisher={IEEE}
}
```

**Comment by TimothyHTimothy** [comment]
Thanks Zhengtong for pointing that out!
We will modify it in our camera ready.
