### ISSUE TITLE
config file seems not compatible with the vqa.py

### ISSUE THREAD

**Issue by zhangxixi0904** [TimothyHTimothy/FAST-VQA#20]
Hi, when running vaq.py to inference a single mp4 file with default config file options/fast/f3dvqa-b.yml,  it will produce an error:

Traceback (most recent call last):
  File "/data4/xxx/VideoQualiry/FAST-VQA-and-FasterVQA/vqa.py", line 62, in <module>
    sampler = SampleFrames(clip_len = t_data_opt["clip_len"], num_clips = t_data_opt["num_clips"])
KeyError: 'clip_len

Has the data structure in f3dvqa-b.yml been modified? How should I fix it.

**Comment by teowu** [comment]
This issue is fixed, please see the newest version.
