### ISSUE TITLE
train

### ISSUE THREAD

**Issue by Nirvana-feng** [TimothyHTimothy/FAST-VQA#21]
Hello, I want to ask that you can only train under the LSVQ data set when training. If so, you can share a data set with me. The official connection cannot download it.

**Comment by teowu** [comment]
Hi. Would like to help but it is not our copyright to do so.
My suggestion is to contact the official authors (way here: [github.com/baidut/PatchVQ](github.com/baidut/PatchVQ)) and ask them to restore the access to download LSVQ.
I also met similar situation months ago and asked them, and they restored the access.

**Comment by teowu** [comment]
(tip: You may cc the corresponding author Prof. Alan C. Bovik to get faster response by original author)

**Comment by Nirvana-feng** [comment]
Okay Thank you
