### ISSUE TITLE
KeyErrors

### ISSUE THREAD

**Issue by Vincent6896** [TimothyHTimothy/FAST-VQA#22]
File "/mnt/disk10T/wch/Faster_VQA1/fastvqa/datasets/fusion_datasets.py", line 535, in __init__
    self.samplers[stype] = FragmentSampleFrames(sopt["clip_len"], sopt["num_clips"], sopt["frame_interval"])
KeyError: 'clip_len'

There are several keyerrors that occur in the code, may I ask how to change the code to solve the problem? In addition, may I ask if there is something else in the code that need to change and add? Thank you very much.

**Comment by teowu** [comment]
Hi Vincent,
Sorry about that.
May I know which command you are running?

We will try to solve this problem ASAP.

**Comment by teowu** [comment]
This is fixed, please run ```git pull``` to fix this. (This error happens because some config files was still designed for the older version).

**Comment by Vincent6896** [comment]
> Hi. Thank you very much. But when running new_train.py, it will still cause KeyError: 'clip_len'. I attached the error message. It seems that in fusion_datasets.py, the sopt variable does not contain some keys like sopt["clip_len"], sopt["num_clips"], sopt["frame_interval"]. May I ask if I clone the code directly, how could I make it run smoothly? In addition, the link for downloading KoNViD_1k does not work, may I ask could you please share some method to download it? Lastly, the downloaded pretrained_weights should all be put into one folder like what was done in the old_master? Thank you very much.

<img width="897" alt="Screenshot 2022-12-02 at 7 26 18 PM" src="https://user-images.githubusercontent.com/89310275/205282544-9979b39e-51b5-4e1a-99f3-8719d84ef67a.png">

**Comment by teowu** [comment]
Have DMed you to solve this.
