### ISSUE TITLE
OSError: [Errno 22] Invalid argument: './pretrained_weights/FAST_VQA_3D_1*1.pth'

### ISSUE THREAD

**Issue by AdrienSchadle** [TimothyHTimothy/FAST-VQA#24]
Hi,

I try to use your tool to evaluate quality of some videos of mine. The error "OSError: [Errno 22] Invalid argument: './pretrained_weights/FAST_VQA_3D_1*1.pth'" occurs. 

Step to reproduce the issue:
python vqa.py

I've seen in the github release the files  "FAST_VQA_3D_1_1_Scr.pth" and "FAST_VQA_B_1_4_Scr.pth", but with my OS (Windows 10 or Ubuntu 20.04), I can't rename those files because of the char  '*' in the name of the file "FAST_VQA_3D_1*1.pth"

Can you tell me what is wrong in my use of your application ?

Regards,
Adrien Schadle

**Comment by teowu** [comment]
Hi, Adrien!

Sorry for the late reply!
You may change the last line in options/fast/f3dvqa-b.yml into 
`test_load_path: pretrained_weights/FAST_VQA_3D_1_1.pth` (btw if it is for better accuracy please do not use the one with the suffix `scr` as this is the ablation version without pre-training)
and keep the file name unchanged for your downloaded file.
That will work.

**Comment by AdrienSchadle** [comment]
It's my turn to reply lately :-)

Thanks a lot, it seems ok.
