### ISSUE TITLE
No results obtained for testing 

### ISSUE THREAD

**Issue by dmumtaz** [TimothyHTimothy/FAST-VQA#27]
I am trying to run the **python3 vqa.py**  file but it seems to get struck after "Setting backbone"
Do I need to download anything else apart from your git repository for testing the video?

Args are: Namespace(device='cuda', model='FasterVQA', video_path='./demos/10053703034.mp4')
backbone_size: swin_tiny_grpb
/home/user/.local/lib/python3.8/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]

Setting backbone: fragments_backbone

**Comment by dmumtaz** [comment]
It seems there was issue related to Cuda,
I replaced the default device to cpu in **[vqa.py](vqa.py)** and that worked.

**Comment by muhammad-faizan-122** [comment]
I also found same issue as mentioned above. Also tested with cpu.
