### ISSUE TITLE
How to draw Fig.9

### ISSUE THREAD

**Issue by winwinwenwen77** [TimothyHTimothy/FAST-VQA#29]
Hi,

How can we draw the quality maps as shown in Fig.9? Will the codes for the maps be released? Could you please provide some instructions?

**Comment by teowu** [comment]
Yes, this was released. Please refer to the old-master branch's visualize.py to see how to use them.
We will try to migrate this to the refactorized new branch in the future.

**Comment by winwinwenwen77** [comment]
Thank you!
