### ISSUE TITLE
I think some part of the code is missing?

### ISSUE THREAD

**Issue by LahiruJayasinghe** [TimothyHTimothy/FAST-VQA#3]
https://github.com/TimothyHTimothy/FAST-VQA/blob/2b579bd10daa903e0670023938bf530c9e797c26/iqassesor.py#L71

**Comment by teowu** [comment]
Yes. This is because we deprecated the building of IQA based on fragments.
However, we have built the dataset APIs for this and you might have a try if you are interested in it.

**Comment by LahiruJayasinghe** [comment]
I see, understand, thanks for the info
