### ISSUE TITLE
Issue in "VQA.py" file

### ISSUE THREAD

**Issue by joker2411** [TimothyHTimothy/FAST-VQA#32]
In your repo, you have mentioned that to check the quality of a single video in the range of [0,1] , we can use "vqa.py" file. So, I am using that file and performing a different study for that I need the video quality assessment task. I have written my code and performed everything but the only problem that I am getting is --
I have trained FasterVQA on my dataset but when I am accessing the quality of a single video using "vqa.py" file with the help of my trained network, in line 17 and 98, you have hardcoded the mean and std which are specific to your models. Since my model is trained on my dataset it is not performing well with these mean and std as compared to their corresponding pretrained model.
I just want to know how can i find mean and std specific to my trained model?

**Comment by teowu** [comment]
Hi Joker,

You may refer to the following code to get mean and variance for predictions on your datasets:

```python
def rescale(pr, gt=None):
   print("mean", np.mean(pr), "std", np.std(pr))
   pr = (pr - np.mean(pr)) / np.std(pr)
   return pr
```

You may hard-code then with the printed results.
