### ISSUE TITLE
LSVQ database

### ISSUE THREAD

**Issue by hello02world** [TimothyHTimothy/FAST-VQA#5]
I wanted to download LSVQ database, but the colab official website is not be open. Do you have any download path？Can you share with me？

**Comment by teowu** [comment]
We have this database but we wonder whether we can be able to share this without permission from LIVE-Lab, the original collector for it. This is a copyright-related issue and we must take care.

My suggestion is that you may ask Zhenqiang Ying (author of LSVQ/PVQ) by email to obtain the download path, or if permitted by him or other authors, you can come back to us and we will share our collection.

Best.
