### ISSUE TITLE
Why the output scores are weird like [-0.05591499]?

### ISSUE THREAD

**Issue by Mmmmmmmag** [TimothyHTimothy/FAST-VQA#7]
Hi, I downloaded the fast_vqa_v0_3.pth and A001.mp4 as the input video, then ran the inference.py and fast_vqa_model.py, but with both of them the output scores are weird like [-0.05591499], so that cannot compute srocc with label score, for example, [80.232]. Is there anything wrong did I do...?

**Comment by teowu** [comment]
Hi, to compute SRCC/PLCC, more than two videos (for better evaluation, more than 50 is recommended) are needed.

Please try to add A002.mp4 or use the full LIVE-VQC instead.

Best,
Haoning
