### ISSUE TITLE
final output score: qlt_score in the line 36 of fastvqa/models/head.py is a small decimal which is < 0

### ISSUE THREAD

**Issue by Mmmmmmmag** [TimothyHTimothy/FAST-VQA#8]
Hi, In line 36 of fastvqa/models/head.py, the qlt_score seems to be the final output score tensor, but it is a small decimal which is < 0, so should I do math.exp(qlt_score) or something else? So that I can get the final score in the range of (0,100)? Thanks a lot and looking forward to your apply!

**Comment by teowu** [comment]
Yes you may need some rescaling, and a possible rescaling factor can be 
```python
a1, a2, a3, a4 = -0.08283314, 0.037915636, 17.057644220869555, 63.291117743589744
def rescale(x):
    return ((x - a1) / a2) * a3 + a4
```
where `x` is the original output score of the model.
Best.
